development:
  facebook_api_key: your_development_key
  facebook_api_secret: your_development_secret

production:
  facebook_api_key: your_production_secret
  facebook_api_secret: your_development_secret